### ISSUE TITLE
Failed to create csvserver

### ISSUE THREAD

**Issue by ONordander** [netscaler/netscaler-k8s-ingress-controller#551]
**Describe the bug**
Hi, I have installed the citrix-ingress-controller in my Kubernetes cluster and when trying to create an Ingress it throws an error of:
`2022-08-06 10:09:20,721  - ERROR - [nitrointerface.py:_create_nsapp_cs_vserver:3575] (MainThread) Failed to create csvserver <prefix-frontend-ip_80_http> errorcode=273,message=Resource already exists`
In the UI I can't see that the server exists, so I'm not sure whats going on.

I also tried to change the `NS_APPS_NAME_PREFIX` to make sure it definitely doesn't exist but that doesn't help either.

**To Reproduce**
citrix-k8s-ingress-controller:1.26.7
Ingress:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    <certificate-annotation>
    ingress.citrix.com/frontend-ip: <frontend-ip>
    ingress.citrix.com/insecure-termination: redirect
    ingress.citrix.com/servicegroup: '{"<service-name>":{"netprofile":<netprofile>}}'
  name: <service-name>
spec:
  rules:
  - host: <hostname>
    http:
      paths:
      - backend:
          service:
            name: <service-name>
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - <hostname>
    secretName: <service-name>-cert

```
**Expected behavior**
No errors and a successful creation of CS VServer.

**Logs**
`2022-08-06 10:09:20,721  - ERROR - [nitrointerface.py:_create_nsapp_cs_vserver:3575] (MainThread) Failed to create csvserver <prefix-frontend-ip_80_http> errorcode=273,message=Resource already exists`

**Additional context**
I'm running multiple ingress-controllers in different clusters if that might give any indication.
