### ISSUE TITLE
Service Group IP not updating after an application rolled out when NS_SNIPS used

### ISSUE THREAD

**Issue by arasyor** [netscaler/netscaler-k8s-ingress-controller#635]
Service Group IP's not updating with new pod IPs when application rolled out on k8s ingress controller installed OpenShift cluster with NS_SNIPS option.

OpenShift version 4.12.34 with OpenShift SDN CNI.

netscaler-k8s-ingress-controller operator object below. Ingress Controller image tag 1.39.6 is used.

```
kind: NetscalerIngressController
apiVersion: netscaler.com/v1
metadata:
  name: nsic
  namespace: netscaler-ingress-controller
spec:
  adcCredentialSecret: nslogin-local
  affinity: {}
  analyticsConfig:
    distributedTracing:
      enable: false
      samplingrate: 100
    endpoint:
      server: ''
      service: ''
    required: false
    timeseries:
      auditlogs:
        enable: false
      events:
        enable: false
      metrics:
        enable: false
        enableNativeScrape: false
        exportFrequency: 30
        mode: avro
        schemaFile: schema.json
      port: 30002
    transactions:
      enable: false
      port: 30001
  clusterName: ocptstinf01
  crds:
    install: true
    retainOnDelete: false
  defaultSSLCertSecret: nsic-tst-cert
  disableAPIServerCertVerify: false
  disableOpenshiftRoutes: false
  entityPrefix: openshift
  exporter:
    extraVolumeMounts: []
    image: >-
      {{ .Values.exporter.imageRegistry }}/{{ .Values.exporter.imageRepository
      }}:{{ .Values.exporter.imageTag }}
    imageRegistry: quay.io
    imageRepository: netscaler/netscaler-adc-metrics-exporter
    imageTag: 1.4.9
    ports:
      containerPort: 8888
    pullPolicy: IfNotPresent
    required: false
    resources: {}
    serviceMonitorExtraLabels: {}
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: ''
  ignoreNodeExternalIP: false
  image: >-
    {{ .Values.imageRegistry }}/{{ .Values.imageRepository }}:{{
    .Values.imageTag }}
  imagePullSecrets: []
  imageRegistry: quay.io
  imageRepository: netscaler/netscaler-k8s-ingress-controller
  imageTag: 1.39.6
  ingressClass:
    - netscaler
  ipam: false
  jsonLog: false
  kubernetesURL: ''
  license:
    accept: 'yes'
  logLevel: INFO
  logProxy: ''
  nameOverride: ''
  namespaceLabels: ''
  nitroReadTimeout: 20
  nodeSelector:
    key: node-role.kubernetes.io/infra
    value: ''
  nodeWatch: true
  nsConfigDnsRec: false
  nsCookieVersion: '0'
  nsDnsNameserver: ''
  nsEnableLabel: true
  nsHTTP2ServerSide: 'OFF'
  nsIP: 10.81.22.10
  nsLbHashAlgo:
    hashAlgorithm: DEFAULT
    hashFingers: 256
    required: false
  nsPort: 443
  nsProtocol: HTTPS
  nsSNIPS: '["10.79.94.56"]'
  nsSvcLbDnsRec: false
  nsVIP: 10.79.94.55
  nsncPbr: false
  openshift: true
  optimizeEndpointBinding: false
  podAnnotations: {}
  podIPsforServiceGroupMembers: false
  profileHttpFrontend: {}
  profileSslFrontend: {}
  profileTcpFrontend: {}
  pullPolicy: IfNotPresent
  rbacRole: false
  resources:
    limits: {}
    requests:
      cpu: 32m
      memory: 128Mi
  routeLabels: 'netscaler-ingress-controller=true'
  secretStore:
    enabled: false
    password: {}
    username: {}
  serviceAccount:
    create: true
  serviceClass: []
  setAsDefaultIngressClass: false
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
    operator: Exists
  updateIngressStatus: true
```

OpenShift route object below.

```
kind: Route
metadata:
  labels:
    netscaler-ingress-controller: "true"
  name: python-test-app-nsic
  namespace: opensol-dev-infra
spec:
  host: python-test-app.nsic.ocptst.local
  port:
    targetPort: 8080
  to:
    kind: Service
    name: python-test-app
    weight: 100
  wildcardPolicy: None
```

Netscaler LB vserver after route object created below.

```
> show lb vserver openshift-python-test-app_8080_lbv_57fkxi7vr25aap47oq2vsb4jo2dm3yvr
        openshift-python-test-app_8080_lbv_57fkxi7vr25aap47oq2vsb4jo2dm3yvr (0.0.0.0:0) - HTTP  Type: ADDRESS 
        State: UP
        Last state change was at Mon Feb 26 14:11:08 2024
        Time since last state change: 0 days, 00:00:04.130
        Effective State: UP  ARP:DISABLED
        Client Idle Timeout: 180 sec
        Down state flush: ENABLED
        Disable Primary Vserver On Down : DISABLED
        Comment: "rv:2116328244,ing:python-test-app-nsic,ingport:80,ns:opensol-dev-infra,svc:python-test-app,svcport:8080"
        Appflow logging: ENABLED
        Port Rewrite : DISABLED
        No. of Bound Services :  2 (Total)       1 (Active)
        Configured Method: LEASTCONNECTION
        Current Method: Round Robin, Reason: Bound service's state changed to UP        BackupMethod: ROUNDROBIN
        Mode: IP
        Persistence: NONE
        Vserver IP and Port insertion: OFF 
        Push: DISABLED  Push VServer: 
        Push Multi Clients: NO
        Push Label Rule: none
        L2Conn: OFF
        Skip Persistency: None
        Listen Policy: NONE
        IcmpResponse: PASSIVE
        RHIstate: PASSIVE
        New Service Startup Request Rate: 0 PER_SECOND, Increment Interval: 0
        Mac mode Retain Vlan: DISABLED
        DBS_LB: DISABLED
        Process Local: DISABLED
        Traffic Domain: 0
        TROFS Persistence honored: ENABLED
        Retain Connections on Cluster: NO
        Order Sequence: ASCENDING
        Current Active Order: None

Bound Service Groups:
1)      Group Name: openshift-python-test-app_8080_sgp_57fkxi7vr25aap47oq2vsb4jo2dm3yvr

                1) openshift-python-test-app_8080_sgp_57fkxi7vr25aap47oq2vsb4jo2dm3yvr (10.90.19.155: 8080) - HTTP State: UP    Weight: 1 Order: None
                2) openshift-python-test-app_8080_sgp_57fkxi7vr25aap47oq2vsb4jo2dm3yvr (10.90.19.22: 8080) - HTTP State: DOWN   Weight: 1 Order: None
 Done
```

Pod IPs of deployment below.

```
NAME                               READY   STATUS    RESTARTS   AGE   IP          
python-test-app-6556f98896-dg98z   1/1     Running   0          40m   10.90.19.155
```

After deployment rolled out, new pods are created with new IPs but Service Group IPs not changed and vserver down.

```
NAME                               READY   STATUS        RESTARTS   AGE   IP          
python-test-app-6556f98896-dg98z   1/1     Terminating   0          41m   10.90.19.155
python-test-app-7cc45d498b-vdgc7   1/1     Running       0          3s    10.90.19.157
```

```
> show lb vserver openshift-python-test-app_8080_lbv_57fkxi7vr25aap47oq2vsb4jo2dm3yvr
        openshift-python-test-app_8080_lbv_57fkxi7vr25aap47oq2vsb4jo2dm3yvr (0.0.0.0:0) - HTTP  Type: ADDRESS 
        State: DOWN
        Last state change was at Mon Feb 26 14:12:26 2024
        Time since last state change: 0 days, 00:02:41.770
        Effective State: DOWN  ARP:DISABLED
        Client Idle Timeout: 180 sec
        Down state flush: ENABLED
        Disable Primary Vserver On Down : DISABLED
        Comment: "rv:2116328244,ing:python-test-app-nsic,ingport:80,ns:opensol-dev-infra,svc:python-test-app,svcport:8080"
        Appflow logging: ENABLED
        Port Rewrite : DISABLED
        No. of Bound Services :  2 (Total)       0 (Active)
        Configured Method: LEASTCONNECTION
        Current Method: Round Robin, Reason: Bound service's state changed to UP        BackupMethod: ROUNDROBIN
        Mode: IP
        Persistence: NONE
        Vserver IP and Port insertion: OFF 
        Push: DISABLED  Push VServer: 
        Push Multi Clients: NO
        Push Label Rule: none
        L2Conn: OFF
        Skip Persistency: None
        Listen Policy: NONE
        IcmpResponse: PASSIVE
        RHIstate: PASSIVE
        New Service Startup Request Rate: 0 PER_SECOND, Increment Interval: 0
        Mac mode Retain Vlan: DISABLED
        DBS_LB: DISABLED
        Process Local: DISABLED
        Traffic Domain: 0
        TROFS Persistence honored: ENABLED
        Retain Connections on Cluster: NO
        Order Sequence: ASCENDING
        Current Active Order: None

Bound Service Groups:
1)      Group Name: openshift-python-test-app_8080_sgp_57fkxi7vr25aap47oq2vsb4jo2dm3yvr

                1) openshift-python-test-app_8080_sgp_57fkxi7vr25aap47oq2vsb4jo2dm3yvr (10.90.19.155: 8080) - HTTP State: DOWN  Weight: 1 Order: None
                2) openshift-python-test-app_8080_sgp_57fkxi7vr25aap47oq2vsb4jo2dm3yvr (10.90.19.22: 8080) - HTTP State: DOWN   Weight: 1 Order: None
 Done
```

On previous images with tag 1.33.x, when image name was Citrix Ingress Controller, this feature was working but it is not working now with Netscaler Ingress Controller.
