### ISSUE TITLE
Authpolicy with `//` double slashes not working

### ISSUE THREAD

**Issue by enov** [netscaler/netscaler-k8s-ingress-controller#644]
**Describe the bug**
Authpolicy with `//` double slashes not working. When we want to secure `/api` but allow `/`, Citrix allows connections to everything under `//*` (for ex: `//api/v1/ping`). To deny `//*` we are adding `//` to the paths along with `/api` but it's not working.

**Slack Channel**
Invitation requested.

**To Reproduce**
1. Add an auth policy with the following spec:
```
spec:
  authentication_policies:
    - provider:
        - jwt
      resource:
        method:
          - GET
        path:
          - //
          - /api
    - provider: []
      resource:
        method:
          - GET
        path:
          - /
```
2. Version of the Citrix Ingress Controller: NS13.0 92.21.nc
3. Version of MPX/VPX/CPX: ADC VPX 200 (?)
4. Environment variables (minus secrets): n/a

**Expected behavior**
We would like to see `//*` auth policy enabled when `//` is added to the paths.

**Logs**
n/a

**Additional context**
