### ISSUE TITLE
IPAM Controller not creating VIP custom resource when using annotation service.citrix.com/frontend-ip

### ISSUE THREAD

**Issue by philipp1992** [netscaler/netscaler-k8s-ingress-controller#674]
**Describe the bug**
We create a service that should use a static vip via the annotation service.citrix.com/frontend-ip: <ip>.
This works and the service loadbalancer is reachable.
Unfortunately, no VIP CR is created and therefore we had the issue, that the IPAM controller didnt know this ip was already in use and assigned it to another service loadbalancer, thus creating a conflict.

When we first create the vip cr manually and then omit the annotation on the service, it works as expected.

**To Reproduce**
1. Steps

```
kind: Service
apiVersion: v1
metadata:
  name: test-lb
  namespace: xxxx
  annotations:
    service.citrix.com/frontend-ip: xxx
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: acme-http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
  internalTrafficPolicy: Cluster

  allocateLoadBalancerNodePorts: true
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/instance: xxxx
```

2. Version of the NetScaler Ingress Controller
ingress-controller: 1.39.6
ipam-controller: 1.0.3

4. Version of MPX/VPX/CPX
NS14.1 25.56.nc

**Expected behavior**
A VIP being created so that the ip can not be reused for other services.

**Logs**

kubectl logs 

ipam controller isnt logging any errors or information in this case

kind regards
Philipp
